[env:m5stack-core2]
platform = espressif32
board = m5stack-core2
framework = arduino
build_unflags = -std=gnu++11
build_flags = -std=gnu++2a
lib_deps =
    m5stack/M5Unified
    https://github.com/skypjack/entt.git#v3.8.0
